export interface BungieInfo {
  membershipId?: number | string;
  uniqueName?: string;
  normalizedName?: string;
  displayName?: string;
  profilePicture?: number;
  profileTheme?: number;
  userTitle?: number;
  successMessageFlags?: number;
  isDeleted?: boolean;
  about?: string;
  firstAccess?: string;
  lastUpdate?: string;
  legacyPortalUID?: number;
  context?: any;
  psnDisplayName?: string;
  xboxDisplayName?: string;
  fbDisplayName?: string;
  showActivity?: boolean;
  locale?: string;
  localeInheritDefault?: boolean;
  lastBanReportId?: number;
  showGroupMessaging?: boolean;
  profilePicturePath?: string;
  profilePictureWidePath?: string;
  profileThemeName?: string;
  userTitleDisplay?: string;
  statusText?: string;
  statusDate?: string;
  profileBanExpire?: string;
  blizzardDisplayName?: string;
  steamDisplayName?: string;
  stadiaDisplayName?: string;
  twitchDisplayName?: string;
  egsDisplayName?:string;
  cachedBungieGlobalDisplayName?: string;
  cachedBungieGlobalDisplayNameCode?: number;
}
