export const baseConstants = {
  D2DASHBOARD_ACKNOWLEDGE_OFFLINE: 'D2DASHBOARD_ACKNOWLEDGE_OFFLINE',
  PROFILE_UPDATING_EXP_MINUTES: 180,
  MEMBER_RECENT_ACTIVITY_EXP_MINUTES: 360,
  CURRENT_SEALS_HASH: 616318467
};
